"""
Report Generation (Phase 9)

Produces JSON (machine-readable), HTML (human-readable, matches dashboard),
and PDF (forensic/takedown-ready) reports for a completed job.
"""
import json
import logging
from datetime import datetime
from pathlib import Path

from jinja2 import Environment, BaseLoader

from app.models.models import Report

logger = logging.getLogger("clonedetector.report")

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Clone Detection Report — {{ job_id }}</title>
<style>
  body { font-family: -apple-system, Arial, sans-serif; margin: 40px; color: #1a1a1a; }
  h1 { color: #0f172a; }
  .verdict { font-size: 1.1em; padding: 16px; border-radius: 8px; background: #f1f5f9; margin: 16px 0; }
  .metrics { display: flex; gap: 24px; margin: 24px 0; }
  .metric { flex: 1; padding: 16px; border-radius: 8px; text-align: center; color: white; }
  .metric.clone { background: #7c3aed; }
  .metric.risk { background: #dc2626; }
  .metric.confidence { background: #0891b2; }
  .metric .value { font-size: 2em; font-weight: bold; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { text-align: left; padding: 8px; border-bottom: 1px solid #e2e8f0; }
  th { background: #f8fafc; }
  .sev-high { color: #dc2626; font-weight: bold; }
  .sev-medium { color: #d97706; font-weight: bold; }
  .sev-low { color: #65a30d; }
  footer { margin-top: 40px; font-size: 0.85em; color: #64748b; }
</style>
</head>
<body>
  <h1>Fake / Cloned Android App Detection — Analysis Report</h1>
  <p><strong>Analysis ID:</strong> {{ job_id }}<br>
     <strong>Generated:</strong> {{ generated_at }}</p>

  <div class="metrics">
    <div class="metric clone"><div>Clone Probability</div><div class="value">{{ "%.0f"|format(final_score.clone_probability * 100) }}%</div></div>
    <div class="metric risk"><div>Malware Risk</div><div class="value">{{ "%.0f"|format(final_score.malware_risk * 100) }}%</div></div>
    <div class="metric confidence"><div>Confidence</div><div class="value">{{ "%.0f"|format(final_score.confidence * 100) }}%</div></div>
  </div>

  <div class="verdict">{{ final_score.verdict_summary }}</div>

  <h2>APK Metadata</h2>
  <table>
    <tr><th></th><th>Original</th><th>Candidate</th></tr>
    {% for label, key in [("Package", "package_name"), ("App Label", "app_label"), ("Version", "version_name"), ("Cert SHA-256", "cert_sha256"), ("File SHA-256", "file_sha256")] %}
    <tr><td>{{ label }}</td><td>{{ apks.original[key] or "—" }}</td><td>{{ apks.candidate[key] or "—" }}</td></tr>
    {% endfor %}
  </table>

  <h2>Similarity Breakdown</h2>
  <table>
    <tr><th>Signal</th><th>Score</th></tr>
    {% for k, v in final_score.component_scores.items() %}
    <tr><td>{{ k }}</td><td>{{ "%.0f"|format(v * 100) }}%</td></tr>
    {% endfor %}
  </table>

  <h2>Risk Findings</h2>
  {% if risk_findings %}
  <table>
    <tr><th>Type</th><th>Severity</th><th>Source</th><th>Evidence</th></tr>
    {% for f in risk_findings %}
    <tr>
      <td>{{ f.finding_type }}</td>
      <td class="sev-{{ f.severity }}">{{ f.severity|upper }}</td>
      <td>{{ f.source_apk or "—" }}</td>
      <td>{{ f.evidence }}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>No suspicious indicators detected.</p>
  {% endif %}

  <h2>Conclusion</h2>
  <p>{{ final_score.verdict_summary }}</p>
  <p><em>This report is generated by automated static analysis for triage/forensic
  support. It combines multiple independent signals and reports a confidence
  level for the evidence available; it is not a substitute for manual expert
  review before any takedown or legal action.</em></p>

  <footer>Fake / Cloned Android App Detection System — Local MVP — generated {{ generated_at }}</footer>
</body>
</html>
"""


def generate_reports(job, storage) -> Report:
    job_id = str(job.id)
    report_dir = Path(storage.job_report_dir(job_id))

    apks = {a.role.value: {
        "package_name": a.package_name, "app_label": a.app_label, "version_name": a.version_name,
        "cert_sha256": a.cert_sha256, "file_sha256": a.file_sha256,
    } for a in job.apk_metadata}

    final_score = job.final_score
    risk_findings = job.risk_findings

    data = {
        "job_id": job_id,
        "generated_at": datetime.utcnow().isoformat(),
        "apks": apks,
        "final_score": {
            "clone_probability": final_score.clone_probability,
            "malware_risk": final_score.malware_risk,
            "confidence": final_score.confidence,
            "component_scores": final_score.component_scores,
            "weights_used": final_score.weights_used,
            "verdict_summary": final_score.verdict_summary,
        },
        "risk_findings": [
            {"finding_type": f.finding_type, "severity": f.severity, "evidence": f.evidence, "source_apk": f.source_apk}
            for f in risk_findings
        ],
    }

    # JSON
    json_path = report_dir / "report.json"
    json_path.write_text(json.dumps(data, indent=2))

    # HTML
    env = Environment(loader=BaseLoader())
    template = env.from_string(HTML_TEMPLATE)
    html_content = template.render(
        job_id=job_id, generated_at=data["generated_at"], apks=apks,
        final_score=data["final_score"], risk_findings=data["risk_findings"],
    )
    html_path = report_dir / "report.html"
    html_path.write_text(html_content)

    # PDF (best-effort — weasyprint needs system libs installed in the Docker image)
    pdf_path = None
    try:
        from weasyprint import HTML
        pdf_dest = report_dir / "report.pdf"
        HTML(string=html_content).write_pdf(str(pdf_dest))
        pdf_path = str(pdf_dest)
    except Exception:
        logger.warning("PDF generation failed — JSON/HTML reports are still available.", exc_info=True)

    return Report(
        job_id=job.id,
        json_path=str(json_path),
        html_path=str(html_path),
        pdf_path=pdf_path,
        generated_at=datetime.utcnow(),
    )
